### ISSUE TITLE
setHeading not showing

### ISSUE THREAD

**Issue by carlossclaro** [saadahmedscse/Android-Popup-Dialog#2]
The .setHeading does not seem to set a heading on the dialog. 

`  PopupDialog.getInstance(RegisterActivity.this)
                                            .setStyle(Styles.FAILED)
                                            .setHeading("tse")
                                            .setHeading("Error! "+ errorMessage)
                                            .setCancelable(false)
                                            .showDialog(new OnDialogButtonClickListener() {
                                                @Override
                                                public void onDismissClicked(Dialog dialog) {
                                                    super.onDismissClicked(dialog);
                                                }
                                            });`
![image](https://user-images.githubusercontent.com/10821590/217338475-eb0e8783-d27c-4556-b437-01bf891a9e56.png)

**Comment by carlossclaro** [comment]
Fix corrected in #3.

**Comment by saadahmedscse** [comment]
You are setting heading two times and the second one is showing.. The
should only be 1 setHeading() function..

**Comment by saadahmedscse** [comment]
I see there is a mistake made by me.. It will be fixed soon.
